# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/contracts

commands:
  install_vyper:
    description: "Install Vyper"
    steps:
      - run:
          name: Install Vyper
          command: |
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get install build-essential libssl-dev libffi-dev
            wget https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
            tar xfz Python-3.6.2.tgz
            cd Python-3.6.2/
            ./configure --prefix /usr/local/lib/python3.6
            sudo make
            sudo make install
            echo 'export PATH="$HOME/.local/bin:/usr/local/lib/python3.6/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            pip3.6 install --user vyper
  install_deps:
    description: "Install dependencies"
    steps:
      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save node_modules
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor: default
    steps:
      - checkout
      - install_vyper
      - install_deps
      - run:
          name: Run tests
          command: npm run coverage

workflows:
  build:
    jobs:
      - build
